[book]
authors = ["Martin Geisler"]
language = "en"
multilingual = false
src = "src"
title = "Comprehensive Rust 🦀"

[rust]
edition = "2021"

[preprocessor.svgbob]
class = "bob"

[output.html]
curly-quotes = true
additional-js = ["ga4.js"]

[output.html.fold]
enable = true
level = 0

[output.html.playground]
editable = true
