name: Build and Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Install mdbook
        run: cargo install mdbook

      - name: Install mdbook-svgbob
        run: cargo install mdbook-svgbob

      - name: Test code snippets
        run: mdbook test
